In [5]:
import keras
from keras.datasets import mnist
from keras.layers import Dense
from keras.models import Sequential

(xtrain,ytrain), (xtest,ytest)= mnist.load_data()
print(len(xtest[0][0]))

print("train data shape: ",xtrain.shape)
print("test data shape : ",xtest.shape)

img_vec_size = 28*28

xtrain=xtrain.reshape(xtrain.shape[0],img_vec_size)
print(xtrain)

xtest=xtest.reshape(xtest.shape[0],img_vec_size)
print(len(xtest[0]))

print("train label shape: ",ytrain.shape)

print("first five training labels: ",ytrain[:5])

num_classes = 10
ytrain=keras.utils.to_categorical(ytrain, num_classes)
ytest = keras.utils.to_categorical(ytest,num_classes)
print(ytrain[:5])

28
train data shape:  (60000, 28, 28)
test data shape :  (10000, 28, 28)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
784
train label shape:  (60000,)
first five training labels:  [5 0 4 1 9]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [6]:



img_size = 784
model = Sequential()

model.add(Dense(units = 1000, activation = 'sigmoid', input_shape = (img_size,)))
model.add(Dense(units = num_classes, activation = 'softmax'))
model.summary()

model.compile(optimizer="sgd", loss="categorical_crossentropy", metrics=['accuracy'])
history = model.fit(xtrain, ytrain, batch_size=128, epochs=15, verbose=False, validation_split=.1)
loss, accuracy = model.evaluate(xtest, ytest, verbose=False)

print(f'test loss: {loss:}')

print(f'Test accuracy: {accuracy:}')

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 1000)              785000    
_________________________________________________________________
dense_6 (Dense)              (None, 10)                10010     
Total params: 795,010
Trainable params: 795,010
Non-trainable params: 0
_________________________________________________________________
test loss: 0.151
Test accuracy: 0.956
